site_name: Stash-Docs
site_url: https://docs.stashapp.cc
site_description: >-
  Stash documentation, guides, plugins and support.

repo_name: stashapp/Stash-Docs
repo_url: https://github.com/stashapp/Stash-Docs
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2017 - 2024 stashapp contributors

theme:
  name: material
  logo: assets/images/logo_white.svg
  custom_dir: overrides
  features:
    - header.autohide
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
#    - content.code.copy
#    - content.code.annotate 
#    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.top
#    - navigation.footer
    - navigation.indexes
    - content.tooltips
#    - content.tabs.link
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      #primary: indigo
      #accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      #primary: red
      #accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/images/favicon.ico

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: stashapp/Stash-Docs
      branch: main
      enabled: !ENV [CI, false]
  - glightbox
  - social:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps:
        'metadata-sources/list.md': 'https://stashapp.github.io/CommunityScrapers'
        'beginner-guides/exclude-file-configuration.md': 'in-app-manual/configuration.md'
        'add-ons.md': 'plugins/index.md'
        'faq/setup.md': 'https://discourse.stashapp.cc/t/-/1658'

watch:
  - includes

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      url_download: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.saneheaders
  - pymdownx.keys
  #- pymdownx.magiclink:
      #repo_url_shortener: true
      #repo_url_shorthand: false
      #user: stashapp
      #repo: Stash-Docs

nav:
  - Home: index.md
  - Installation:
    - installation/index.md
    - Windows: installation/windows.md
    - macOS: installation/macos.md
    - Linux: installation/linux.md
    - Docker: installation/docker.md
    - Synology: installation/synology.md
    - TrueNAS: installation/truenas.md
    - Unraid: installation/unraid.md
    - Getting started: 
      - First steps: getting-started/first-steps.md
  - In-app manual:
    - in-app-manual/index.md
    - Introduction: in-app-manual/introduction.md
    - Configuration: in-app-manual/configuration.md
    - Interface options: in-app-manual/interface.md
    - Tasks:
      - in-app-manual/tasks/index.md
      - Identify: in-app-manual/tasks/identify.md
      - Auto tagging: in-app-manual/tasks/autotagging.md
      - Scene filename parser: in-app-manual/tasks/scenefilenameparser.md
      - Import/export JSON specification: in-app-manual/tasks/jsonspec.md
    - Browsing: in-app-manual/browsing.md
    - Images and galleries: in-app-manual/images.md
    - Metadata scraping:
      - in-app-manual/scraping/index.md
      - Contributing scrapers: in-app-manual/scraping/scraperdevelopment.md
    - Plugins:
      - in-app-manual/plugins/index.md
      - External plugins: in-app-manual/plugins/externalplugins.md
      - Embedded plugins: in-app-manual/plugins/embeddedplugins.md
      - UI plugin API: in-app-manual/plugins/uipluginapi.md
    - Scene tagger: in-app-manual/tagger.md
    - Dupe checker: in-app-manual/deduplication.md
    - Interactivity: in-app-manual/interactive.md
    - Captions: in-app-manual/captions.md
    - Keyboard shortcuts: in-app-manual/keyboardshortcuts.md
    - Ways to contribute: in-app-manual/contributing.md
  - Guides: 
    - guides/index.md
    - Scraping scenes via stash-box: guides/scraping-scenes-via-stash-box.md
    - Backup and restore database: guides/backup-and-restore-database.md
    - Reverse proxy: guides/reverse-proxy.md
    - Troubleshooting video playback: guides/troubleshooting-video-playback.md
    - Run CDP on TrueNAS Scale: guides/run-cdp-on-truenas-scale.md
    - Advanced configuration options: guides/advanced-configuration-options.md
    - Bulk importing via CSV using gql-iterate: guides/importing-via-csv-using-gql-iterate.md
    - Manually editing the Stash sqlite3 database: guides/manually-editing-the-stash-sqlite3-database.md
    - Scraping metadata behind login: guides/scraping-metadata-behind-login.md
  - Metadata sources: 
    - metadata-sources/index.md
    - stash-box instances: metadata-sources/stash-box-instances.md
    - Scrapers: metadata-sources/scrapers.md
    - Browse scrapers: metadata-sources/list.md
  - Plugins: 
    - plugins/index.md
    - Browse plugins: plugins/list.md
    - Themes:
      - themes/index.md
      - Browse themes: themes/list.md
      - Custom CSS snippets: themes/custom-css-snippets.md
    - Userscripts:
      - userscripts/index.md
      - Browse userscripts: userscripts/list.md
    - Scripts:
      - scripts/index.md
      - Browse scripts: scripts/list.md
    - Utilities:
      - utilities/index.md
      - Browse utilities: utilities/list.md
    - Integrations:
      - integrations/index.md
      - Browse integrations: integrations/list.md
  - API: api.md
  - Community forum: https://discourse.stashapp.cc
  - Code of conduct: code-of-conduct.md

extra:
  social:
    - icon: simple/opencollective
      link: https://opencollective.com/stashapp
    - icon: simple/github
      link: https://github.com/stashapp
    - icon: simple/docker
      link: https://hub.docker.com/r/stashapp/stash
    - icon: simple/discord
      link: https://discord.gg/frQ7qBvB3S
    - icon: simple/discourse
      link: https://discourse.stashapp.cc
    - icon: simple/lemmy
      link: https://discuss.online/c/stashapp

extra_css:
  - stylesheets/extra.css